service_name: 'ubs-mock-services'
service_war_dir: '/opt/ubs-mock-services'
process_name: 'ubs-mock-services'
heartBeatUrl: 'http://localhost'
heart_beat_url_context: 'health'
service_port: '8080'
expose_port: '7007'
target_war_dir: ''
docker_registry: 'us.gcr.io'
project_name: 'ppp-prod'
image_tag_name: 'latest'
properties_template_location: '../templates'
log_verbose_level: 'DEBUG'
log4j2_file_name: 'log4j2.xml'
