spring_profiles_active: 'development'
service_name: 'ubs-mock-services'
service_war_dir: '/opt/ubs-mock-services'
process_name: 'ubs-mock-services'
heartBeatUrl: 'http://localhost'
heart_beat_url_context: 'ubs/mock/health'
service_port: '8080'
expose_port: '7007'
target_war_dir: ''
docker_registry: 'us.gcr.io'
project_name: 'ppp-prod'
image_tag_name: 'latest'
properties_template_location: '../templates'
log_verbose_level: 'DEBUG'
log4j2_file_name: 'log4j2-development.xml'
database_instance: '10.11.100.8'
database_port: '3306'
database_schema_name: 'ubs_mock'
database_username: 'root'
database_password: 'Vuclip@123'
rabbitmq_host: '10.11.100.8'
rabbitmq_port: '5672'
rabbitmq_username: 'jenkins'
rabbitmq_password: 'jenkins123'
ribbon_enabled: 'false'
service_log_level: 'DEBUG'
docker_network: ''
